"""cleanup charge notification request

Revision ID: 85054292224d
Revises: 1962aa10532f
Create Date: 2026-01-27 01:03:27.903374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85054292224d'
down_revision: Union[str, Sequence[str], None] = '1962aa10532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_notification_request', 'captured')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_notification_request', sa.Column('captured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
