"""refund cancellation reason

Revision ID: eaee226c1c2a
Revises: abf0e34b2eb3
Create Date: 2026-01-27 12:08:44.247195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaee226c1c2a'
down_revision: Union[str, Sequence[str], None] = 'abf0e34b2eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund', sa.Column('external_cancellation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund', 'external_cancellation_reason')
    # ### end Alembic commands ###
