"""misc

Revision ID: 9b3337f5f3cf
Revises: 4e5f9382e3eb
Create Date: 2026-01-27 19:25:27.075731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3337f5f3cf'
down_revision: Union[str, Sequence[str], None] = '4e5f9382e3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_request', sa.Column('payment_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('payment_request_payemnt_id_key'), 'payment_request', type_='unique')
    op.create_unique_constraint(None, 'payment_request', ['payment_id'])
    op.drop_constraint(op.f('payment_request_payemnt_id_fkey'), 'payment_request', type_='foreignkey')
    op.create_foreign_key(None, 'payment_request', 'payment', ['payment_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('payment_request', 'payemnt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_request', sa.Column('payemnt_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_request', type_='foreignkey')
    op.create_foreign_key(op.f('payment_request_payemnt_id_fkey'), 'payment_request', 'payment', ['payemnt_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'payment_request', type_='unique')
    op.create_unique_constraint(op.f('payment_request_payemnt_id_key'), 'payment_request', ['payemnt_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('payment_request', 'payment_id')
    # ### end Alembic commands ###
