"""reorganize request tables

Revision ID: 4e5f9382e3eb
Revises: eaee226c1c2a
Create Date: 2026-01-27 19:23:23.318876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5f9382e3eb'
down_revision: Union[str, Sequence[str], None] = 'eaee226c1c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handler_notification_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handler_url', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payemnt_id', sa.Uuid(), nullable=False),
    sa.Column('handler_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payemnt_id'], ['payment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payemnt_id')
    )
    op.drop_table('refund_notification_request')
    op.drop_table('charge_notification_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_notification_request',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_topic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('charge_request_payment_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('charge_request_pkey')),
    sa.UniqueConstraint('payment_id', name=op.f('charge_request_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('refund_notification_request',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_to_topic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('refund_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], name=op.f('refund_request_refund_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('refund_request_pkey')),
    sa.UniqueConstraint('refund_id', name=op.f('refund_request_refund_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('payment_request')
    op.drop_table('handler_notification_request')
    # ### end Alembic commands ###
