"""misc

Revision ID: 609a42069405
Revises: 842bbeb6918f
Create Date: 2026-01-24 20:50:44.351402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609a42069405'
down_revision: Union[str, Sequence[str], None] = '842bbeb6918f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('refund_request', 'refunded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('refunded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('refund', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
