"""refund

Revision ID: 842bbeb6918f
Revises: d9a84a17a06c
Create Date: 2026-01-24 15:55:17.382804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842bbeb6918f'
down_revision: Union[str, Sequence[str], None] = 'd9a84a17a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('created', 'succeeded', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_refund_external_id'), 'refund', ['external_id'], unique=False)
    op.create_index(op.f('ix_refund_id'), 'refund', ['id'], unique=False)
    op.add_column('refund_request', sa.Column('refund_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('refund_request_payment_id_key'), 'refund_request', type_='unique')
    op.create_unique_constraint(None, 'refund_request', ['refund_id'])
    op.drop_constraint(op.f('refund_request_payment_id_fkey'), 'refund_request', type_='foreignkey')
    op.create_foreign_key(None, 'refund_request', 'refund', ['refund_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('refund_request', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refund_request', type_='foreignkey')  # type: ignore
    op.create_foreign_key(op.f('refund_request_payment_id_fkey'), 'refund_request', 'payment', ['payment_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'refund_request', type_='unique')  # type: ignore
    op.create_unique_constraint(op.f('refund_request_payment_id_key'), 'refund_request', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('refund_request', 'refund_id')
    op.drop_index(op.f('ix_refund_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_external_id'), table_name='refund')
    op.drop_table('refund')
    # ### end Alembic commands ###
