"""statuses

Revision ID: b1305f4efdb6
Revises: 053058700bf9
Create Date: 2026-01-15 10:28:19.950949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1305f4efdb6'
down_revision: Union[str, Sequence[str], None] = '053058700bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status', sa.Enum('created', 'acking', 'succeeded', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'status')
    # ### end Alembic commands ###
