"""requests processed_at

Revision ID: 4bde927b146e
Revises: d35525f34c7d
Create Date: 2026-01-29 17:01:09.889445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bde927b146e'
down_revision: Union[str, Sequence[str], None] = 'd35525f34c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handler_notification_request', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('handler_notification_request', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_handler_notification_request_created_at'), 'handler_notification_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_handler_notification_request_processed_at'), 'handler_notification_request', ['processed_at'], unique=False)
    op.add_column('payment_request', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payment_request', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_payment_request_created_at'), 'payment_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_request_processed_at'), 'payment_request', ['processed_at'], unique=False)
    op.add_column('refund_request', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('refund_request', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_refund_request_created_at'), 'refund_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_refund_request_processed_at'), 'refund_request', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_request_processed_at'), table_name='refund_request')
    op.drop_index(op.f('ix_refund_request_created_at'), table_name='refund_request')
    op.drop_column('refund_request', 'processed_at')
    op.drop_column('refund_request', 'created_at')
    op.drop_index(op.f('ix_payment_request_processed_at'), table_name='payment_request')
    op.drop_index(op.f('ix_payment_request_created_at'), table_name='payment_request')
    op.drop_column('payment_request', 'processed_at')
    op.drop_column('payment_request', 'created_at')
    op.drop_index(op.f('ix_handler_notification_request_processed_at'), table_name='handler_notification_request')
    op.drop_index(op.f('ix_handler_notification_request_created_at'), table_name='handler_notification_request')
    op.drop_column('handler_notification_request', 'processed_at')
    op.drop_column('handler_notification_request', 'created_at')
    # ### end Alembic commands ###
