"""capture

Revision ID: e61d82c5f571
Revises: e76fd61ccf5f
Create Date: 2026-01-16 11:35:55.933448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61d82c5f571'
down_revision: Union[str, Sequence[str], None] = 'e76fd61ccf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('handler_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_request_id'), 'charge_request', ['id'], unique=False)
    op.create_index(op.f('ix_charge_request_payment_id'), 'charge_request', ['payment_id'], unique=False)
    op.drop_column('payment', 'handler_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_charge_request_payment_id'), table_name='charge_request')
    op.drop_index(op.f('ix_charge_request_id'), table_name='charge_request')
    op.drop_table('charge_request')
    # ### end Alembic commands ###
