"""refund request

Revision ID: 1962aa10532f
Revises: 2218ff1b8fe4
Create Date: 2026-01-27 00:51:07.824859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1962aa10532f'
down_revision: Union[str, Sequence[str], None] = '2218ff1b8fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('refund_id', sa.Uuid(), nullable=False),
    sa.Column('handler_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_request')
    # ### end Alembic commands ###
