"""payment cancellation reason

Revision ID: d35525f34c7d
Revises: edc8061ff5de
Create Date: 2026-01-28 00:03:03.318907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35525f34c7d'
down_revision: Union[str, Sequence[str], None] = 'edc8061ff5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('external_cancellation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'external_cancellation_reason')
    # ### end Alembic commands ###
