"""make handler url optional

Revision ID: abf0e34b2eb3
Revises: 85054292224d
Create Date: 2026-01-27 01:12:29.023954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf0e34b2eb3'
down_revision: Union[str, Sequence[str], None] = '85054292224d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_notification_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refund_notification_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refund_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('refund_notification_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('charge_notification_request', 'handler_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
