"""handler url

Revision ID: 053058700bf9
Revises: ae764c07bcc1
Create Date: 2026-01-15 09:04:21.691532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053058700bf9'
down_revision: Union[str, Sequence[str], None] = 'ae764c07bcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('handler_url', sa.String(), nullable=False))
    op.add_column('payment', sa.Column('amount', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'amount')
    op.drop_column('payment', 'handler_url')
    # ### end Alembic commands ###
