"""delete handlers notification

Revision ID: 6a46f8b4966b
Revises: 4d389329b643
Create Date: 2026-02-01 13:13:44.443354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a46f8b4966b'
down_revision: Union[str, Sequence[str], None] = '4d389329b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handler_notification_request_created_at'), table_name='handler_notification_request')
    op.drop_index(op.f('ix_handler_notification_request_processed_at'), table_name='handler_notification_request')
    op.drop_table('handler_notification_request')
    op.drop_column('payment_request', 'handler_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_request', sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('handler_notification_request',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('handler_notification_request_pkey'))
    )
    op.create_index(op.f('ix_handler_notification_request_processed_at'), 'handler_notification_request', ['processed_at'], unique=False)
    op.create_index(op.f('ix_handler_notification_request_created_at'), 'handler_notification_request', ['created_at'], unique=False)
    # ### end Alembic commands ###
