"""add extra data

Revision ID: edc8061ff5de
Revises: 9b3337f5f3cf
Create Date: 2026-01-27 23:37:46.320230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc8061ff5de'
down_revision: Union[str, Sequence[str], None] = '9b3337f5f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_request', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('refund_request', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_request', 'extra_data')
    op.drop_column('payment_request', 'extra_data')
    # ### end Alembic commands ###
