"""refund

Revision ID: e76fd61ccf5f
Revises: b1305f4efdb6
Create Date: 2026-01-16 10:20:43.701938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e76fd61ccf5f"
down_revision: Union[str, Sequence[str], None] = "b1305f4efdb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refund_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("handler_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refund_request_id"), "refund_request", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refund_request_payment_id"),
        "refund_request",
        ["payment_id"],
        unique=False,
    )
    op.alter_column("payment", column_name="amount", new_column_name="roubles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payment", column_name="roubles", new_column_name="amount")
    op.drop_index(op.f("ix_refund_request_payment_id"), table_name="refund_request")
    op.drop_index(op.f("ix_refund_request_id"), table_name="refund_request")
    op.drop_table("refund_request")
    # ### end Alembic commands ###
