"""refund payment id is not unique

Revision ID: 4d389329b643
Revises: 4bde927b146e
Create Date: 2026-01-29 17:19:39.120773

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4d389329b643'
down_revision: Union[str, Sequence[str], None] = '4bde927b146e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refund_payment_id_key'), 'refund', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('refund_payment_id_key'), 'refund', ['payment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
