"""kafka

Revision ID: d9a84a17a06c
Revises: e4017a6fd34e
Create Date: 2026-01-24 00:36:38.249448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a84a17a06c'
down_revision: Union[str, Sequence[str], None] = 'e4017a6fd34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_request', sa.Column('sent_to_topic', sa.Boolean(), nullable=False))
    op.add_column('refund_request', sa.Column('sent_to_topic', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_request', 'sent_to_topic')
    op.drop_column('charge_request', 'sent_to_topic')
    # ### end Alembic commands ###
