"""refund too

Revision ID: ec7b671e78b6
Revises: 6a46f8b4966b
Create Date: 2026-02-01 13:19:11.294215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7b671e78b6'
down_revision: Union[str, Sequence[str], None] = '6a46f8b4966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_request', 'handler_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('handler_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
