services:

  bill-kafka-0:
    image: apache/kafka:4.1.1
    ports: [ 19092:19092 ]
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: BROKER://:9092,CONTROLLER://:9093,BROKER_EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://bill-kafka-0:9092,BROKER_EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,BROKER_EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@bill-kafka-0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      filebeat_enable: "true"
      service: "bill-kafka-0"

  bill-kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.3.0
    ports: [ 8080:8080 ]
    environment:
      DYNAMIC_CONFIG_ENABLED: true