services:

  bill-postgres:
    image: postgres:18.1-trixie
    environment:
      POSTGRES_USER: ${BILL_POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${BILL_POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${BILL_POSTGRES_DB:?}
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER}
      start_interval: 1s
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432