services:

  bill-api:
    build: .
    env_file:
      - path: .env
        required: false
    environment:
      BILL_POSTGRES_HOST: bill-postgres
      BILL_POSTGRES_PORT: 5432
      BILL_KAFKA_BOOTSTRAP_SERVERS: bill-kafka-0:9092
      BILL_POSTGRES_USER: ${BILL_POSTGRES_USER:?}
      BILL_POSTGRES_PASSWORD: ${BILL_POSTGRES_PASSWORD:?}
      BILL_POSTGRES_DB: ${BILL_POSTGRES_DB:?}
    depends_on:
      bill-postgres:
        condition: service_healthy
      bill-kafka-0:
        condition: service_healthy
    ports: [ 18006:8000 ]

  bill-api-worker-0:
    build: .
    command: .venv/bin/python -m worker
    env_file:
      - path: .env
        required: false
    environment:
      BILL_POSTGRES_HOST: bill-postgres
      BILL_POSTGRES_PORT: 5432
      BILL_KAFKA_BOOTSTRAP_SERVERS: bill-kafka-0:9092
      BILL_POSTGRES_USER: ${BILL_POSTGRES_USER:?}
      BILL_POSTGRES_PASSWORD: ${BILL_POSTGRES_PASSWORD:?}
      BILL_POSTGRES_DB: ${BILL_POSTGRES_DB:?}
    depends_on:
      bill-api:
        condition: service_started