services:

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.tests
    environment:
      BILL_POSTGRES_HOST: postgres
      BILL_POSTGRES_USER: postgres
      BILL_POSTGRES_PASSWORD: postgres
      BILL_POSTGRES_DB: bill
      BILL_KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
    depends_on:
      postgres: { condition: service_healthy }
      kafka-0: { condition: service_healthy }

  postgres:
    image: postgres:18.1-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bill
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER}
      start_interval: 1s
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-0:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: BROKER://:9092,CONTROLLER://:9093,BROKER_EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-0:9092,BROKER_EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,BROKER_EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
