FROM python:3.13.11-slim

COPY --from=ghcr.io/astral-sh/uv:0.9.27 /uv /bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/bill

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-cache --dev

COPY ./pytest.ini ./alembic.ini ./
COPY ./src ./src
COPY ./migrations ./migrations
COPY ./tests/ ./tests

ENV PYTHONPATH=src:tests

CMD [".venv/bin/pytest", "-p", "no:cacheprovider", "--verbose", "--exitfirst", "tests/api"]